version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.2.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:10.2.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm install mocha
      - run: npm install sinon
      - run: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - build
      - test
      - heroku/deploy-via-git:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
