version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.2.1
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: circleci/node:10.2.1
    steps:
      - checkout
      - run: npm install
      - run: npm install mocha
      - run: npm install sinon
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10.2.1
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
